version: "3.1"
services:
  apisprout:
    image: danielgtaylor/apisprout
    volumes:
      - ./stubapi/openapi.yaml:/openapi.yaml
    command: /openapi.yaml
  stubapi:
    image: nginx:mainline-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./stubapi/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apisprout
